package com.ditchoom.buffer.crypto

import com.ditchoom.buffer.BufferFactory
import com.ditchoom.buffer.Default
import com.ditchoom.buffer.PlatformBuffer
import com.ditchoom.buffer.ReadBuffer
import com.ditchoom.buffer.WriteBuffer

/*
 * Authenticated Encryption with Associated Data (AEAD).
 *
 * This file owns the AEAD primitive family: AES-GCM (128/256-bit keys) and ChaCha20-Poly1305
 * (IETF). Each algorithm is wrapped over the platform's native stack — JCA (AES/GCM/NoPadding,
 * ChaCha20-Poly1305) on JVM/Android, CommonCrypto/CryptoKit on Apple, and WebCrypto (AES-GCM)
 * on js/wasmJs. We never hand-roll a primitive; an unavailable algorithm throws
 * UnsupportedOperationException and its capability flag is false.
 *
 * Security contract (uniform across platforms):
 *  - Plaintext is released only after the tag verifies. open() performs a native one-shot
 *    decrypt; there is no unverified-plaintext streaming. A bad tag, tampered ciphertext,
 *    swapped AAD, or wrong key all surface as the same opaque VerificationFailed with no
 *    distinguishing reason — a granular reason on a verify path is a decryption oracle.
 *  - Nonces are CSPRNG-generated by default. The seal helpers draw a fresh 12-byte nonce from
 *    the library CSPRNG and prepend it to the output, so a caller cannot accidentally reuse
 *    one. The explicit-nonce path is internal (the KAT/Wycheproof seam) — reusing a
 *    (key, nonce) pair with GCM or ChaCha20-Poly1305 is catastrophic (see the threat model).
 *  - Fixed 96-bit nonce, fixed 128-bit tag. Any other nonce length is rejected with
 *    IllegalArgumentException; truncated tags are never produced or accepted.
 *  - Typed, sized keys. AesGcmKey carries its 128/256-bit size and ChaChaPolyKey is a distinct
 *    type, so a key for one algorithm/size cannot be silently used for another.
 *
 * Output framing — the self-framing one-shot helpers emit: nonce(12) ‖ ciphertext ‖ tag(16),
 * so the sealed buffer is self-describing and open needs no separate nonce argument. The
 * lower-level seal/open expect functions take ciphertext+tag positioned by the caller within
 * dest; the framing helpers build on them.
 */

/** AEAD nonce/IV length in bytes (96-bit, the only length these wrappers accept). */
const val AEAD_NONCE_BYTES: Int = 12

/** AEAD authentication-tag length in bytes (128-bit, fixed). */
const val AEAD_TAG_BYTES: Int = 16

/** Key length in bytes for AES-128-GCM. */
const val AES_128_KEY_BYTES: Int = 16

/** Key length in bytes for AES-256-GCM. */
const val AES_256_KEY_BYTES: Int = 32

/** Key length in bytes for ChaCha20-Poly1305 (always 256-bit). */
const val CHACHA_KEY_BYTES: Int = 32

private const val SYNC_AES_GCM_UNSUPPORTED = "synchronous AES-GCM is not supported on this platform"

/**
 * An AES-GCM key, carrying its [size] so a 128-bit key can never be silently used where a
 * 256-bit key was meant (or vice versa). Construct via [AesGcmKey.of]; the key bytes are
 * copied into a fresh [PlatformBuffer] so the caller's source buffer is decoupled from the
 * key's lifetime.
 *
 * The key material is **not** auto-wiped — callers that need erase-on-free should allocate
 * the backing buffer from `BufferFactory.deterministic().secure()` and pass it through
 * [of]; the copy taken here preserves that secure backing when the supplied [factory] is
 * secure.
 */
class AesGcmKey private constructor(
    /** 128 or 256 — the AES key size in bits. */
    val sizeBits: Int,
    internal val material: PlatformBuffer,
) : AutoCloseable {
    private var closed = false

    /** Key size in bytes (16 for AES-128, 32 for AES-256). */
    val sizeBytes: Int get() = sizeBits / 8

    /**
     * Zeroes and frees the key material (wipes when [material] is a secure buffer). Idempotent.
     * Parity with the signing/key-agreement key types, which are already [AutoCloseable].
     */
    override fun close() {
        if (!closed) {
            closed = true
            material.freeNativeMemory()
        }
    }

    companion object {
        /**
         * Wraps [key]'s remaining bytes as an AES-GCM key. The length must be exactly 16
         * (AES-128) or 32 (AES-256) bytes; any other length is rejected. The bytes are
         * copied into a buffer from [factory] (use a secure factory for erase-on-free).
         */
        fun of(
            key: ReadBuffer,
            factory: BufferFactory = BufferFactory.Default,
        ): AesGcmKey {
            val n = key.remaining()
            require(n == AES_128_KEY_BYTES || n == AES_256_KEY_BYTES) {
                "AES-GCM key must be $AES_128_KEY_BYTES or $AES_256_KEY_BYTES bytes, was $n"
            }
            return AesGcmKey(n * Byte.SIZE_BITS, copyMaterial(key, factory))
        }
    }
}

/**
 * A ChaCha20-Poly1305 (IETF) key — always 256-bit. A distinct type from [AesGcmKey] so the
 * two AEAD families cannot be cross-used. See [AesGcmKey] for the secure-backing note.
 */
class ChaChaPolyKey private constructor(
    internal val material: PlatformBuffer,
) : AutoCloseable {
    private var closed = false

    /**
     * Zeroes and frees the key material (wipes when [material] is a secure buffer). Idempotent.
     * Parity with the signing/key-agreement key types, which are already [AutoCloseable].
     */
    override fun close() {
        if (!closed) {
            closed = true
            material.freeNativeMemory()
        }
    }

    companion object {
        /**
         * Wraps [key]'s remaining bytes as a ChaCha20-Poly1305 key. The length must be
         * exactly 32 bytes; any other length is rejected. The bytes are copied into a buffer
         * from [factory] (use a secure factory for erase-on-free).
         */
        fun of(
            key: ReadBuffer,
            factory: BufferFactory = BufferFactory.Default,
        ): ChaChaPolyKey {
            val n = key.remaining()
            require(n == CHACHA_KEY_BYTES) {
                "ChaCha20-Poly1305 key must be $CHACHA_KEY_BYTES bytes, was $n"
            }
            return ChaChaPolyKey(copyMaterial(key, factory))
        }
    }
}

/** Copies [source]'s remaining bytes into a fresh read-ready buffer (non-destructive). */
private fun copyMaterial(
    source: ReadBuffer,
    factory: BufferFactory,
): PlatformBuffer = copyBuffer(source, factory)

// =============================================================================
// Low-level one-shot primitives (synchronous, native-or-throw)
// =============================================================================

/**
 * Whether this platform supports the synchronous AES-GCM [aesGcmSeal] / [aesGcmOpen].
 *
 * - JVM, Android, Apple: `true` (JCA / CryptoKit).
 * - js/wasmJs: `false` — WebCrypto's `SubtleCrypto` is async-only; use [aesGcmSealAsync] /
 *   [aesGcmOpenAsync] instead.
 */
expect val supportsSyncAesGcm: Boolean

/**
 * Whether this platform supports ChaCha20-Poly1305 at all.
 *
 * - JVM (11+), Android, Apple: `true`.
 * - js/wasmJs: `false` — ChaCha20-Poly1305 is **not** part of WebCrypto and we never
 *   polyfill it. Both the sync and async ChaCha entry points throw
 *   [UnsupportedOperationException] on the web.
 */
expect val supportsChaChaPoly: Boolean

/**
 * Whether this platform supports the synchronous ChaCha20-Poly1305
 * [chaChaPolySeal] / [chaChaPolyOpen]. Equal to [supportsChaChaPoly] today (no async ChaCha
 * path exists on any current target).
 */
expect val supportsSyncChaChaPoly: Boolean

/**
 * Seals [plaintext] with AES-GCM under [key] and [nonce], writing `ciphertext ‖ tag` into
 * [dest] at its current position (ciphertext length == plaintext length, then [AEAD_TAG_BYTES]
 * of tag). [aad] (associated data, authenticated-not-encrypted) may be `null`/empty.
 *
 * [nonce] must be exactly [AEAD_NONCE_BYTES] bytes. [dest] must have
 * `plaintext.remaining() + AEAD_TAG_BYTES` bytes remaining. The caller is responsible for
 * nonce uniqueness — prefer the framing helper [aesGcmSeal] (with `dest`+`factory`) which
 * generates the nonce.
 *
 * @throws UnsupportedOperationException if [supportsSyncAesGcm] is `false`.
 */
internal expect fun aesGcmSeal(
    key: AesGcmKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    plaintext: ReadBuffer,
    dest: WriteBuffer,
)

/**
 * Opens an AES-GCM `ciphertext ‖ tag` blob ([ciphertextAndTag], whose last [AEAD_TAG_BYTES]
 * bytes are the tag) under [key], [nonce], and [aad], writing the recovered plaintext into
 * [dest]. The plaintext is written **only if the tag verifies**.
 *
 * @throws VerificationFailed if authentication fails (bad tag/ciphertext/AAD/key) — opaque.
 * @throws UnsupportedOperationException if [supportsSyncAesGcm] is `false`.
 */
internal expect fun aesGcmOpen(
    key: AesGcmKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    ciphertextAndTag: ReadBuffer,
    dest: WriteBuffer,
)

/**
 * ChaCha20-Poly1305 counterpart of [aesGcmSeal]. See it for the layout/precondition contract.
 *
 * @throws UnsupportedOperationException if [supportsSyncChaChaPoly] is `false` (e.g. web).
 */
internal expect fun chaChaPolySeal(
    key: ChaChaPolyKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    plaintext: ReadBuffer,
    dest: WriteBuffer,
)

/**
 * ChaCha20-Poly1305 counterpart of [aesGcmOpen]. See it for the verify contract.
 *
 * @throws VerificationFailed if authentication fails — opaque.
 * @throws UnsupportedOperationException if [supportsSyncChaChaPoly] is `false` (e.g. web).
 */
internal expect fun chaChaPolyOpen(
    key: ChaChaPolyKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    ciphertextAndTag: ReadBuffer,
    dest: WriteBuffer,
)

// =============================================================================
// Self-framing one-shot helpers (synchronous) — nonce ‖ ciphertext ‖ tag
// =============================================================================

/**
 * Seals [plaintext] with AES-GCM under [key], generating a fresh CSPRNG nonce and returning a
 * read-ready `nonce ‖ ciphertext ‖ tag` buffer (allocated via [factory]). The matching
 * [aesGcmOpen] framing helper recovers the plaintext with no separate nonce argument.
 *
 * This is the recommended sealing entry point: the nonce is never caller-supplied, so a
 * (key, nonce) pair cannot be accidentally reused.
 *
 * @throws UnsupportedOperationException if [supportsSyncAesGcm] is `false` (use [aesGcmSealAsync]).
 */
fun aesGcmSeal(
    key: AesGcmKey,
    plaintext: ReadBuffer,
    aad: ReadBuffer? = null,
    factory: BufferFactory = BufferFactory.Default,
): PlatformBuffer {
    if (!supportsSyncAesGcm) throw UnsupportedOperationException(SYNC_AES_GCM_UNSUPPORTED)
    val out = allocateFramed(plaintext.remaining(), factory)
    val nonce = writeFreshNonce(out)
    aesGcmSeal(key, nonce, aad, plaintext, out)
    out.resetForRead()
    return out
}

/**
 * Opens a `nonce ‖ ciphertext ‖ tag` buffer produced by [aesGcmSeal], returning the recovered
 * plaintext (allocated via [factory]). Plaintext is returned only if the tag verifies.
 *
 * @throws VerificationFailed if authentication fails — opaque.
 * @throws UnsupportedOperationException if [supportsSyncAesGcm] is `false` (use [aesGcmOpenAsync]).
 */
fun aesGcmOpen(
    sealed: ReadBuffer,
    key: AesGcmKey,
    aad: ReadBuffer? = null,
    factory: BufferFactory = BufferFactory.Default,
): PlatformBuffer {
    if (!supportsSyncAesGcm) throw UnsupportedOperationException(SYNC_AES_GCM_UNSUPPORTED)
    val (nonce, ctAndTag, ptLen) = splitFramed(sealed)
    val out = factory.allocate(ptLen)
    aesGcmOpen(key, nonce, aad, ctAndTag, out)
    out.resetForRead()
    return out
}

/**
 * ChaCha20-Poly1305 self-framing seal — see [aesGcmSeal]. Generates a fresh CSPRNG nonce.
 *
 * @throws UnsupportedOperationException if [supportsSyncChaChaPoly] is `false` (e.g. web — never polyfilled).
 */
fun chaChaPolySeal(
    key: ChaChaPolyKey,
    plaintext: ReadBuffer,
    aad: ReadBuffer? = null,
    factory: BufferFactory = BufferFactory.Default,
): PlatformBuffer {
    if (!supportsSyncChaChaPoly) {
        throw UnsupportedOperationException("ChaCha20-Poly1305 is not supported on this platform")
    }
    val out = allocateFramed(plaintext.remaining(), factory)
    val nonce = writeFreshNonce(out)
    chaChaPolySeal(key, nonce, aad, plaintext, out)
    out.resetForRead()
    return out
}

/**
 * ChaCha20-Poly1305 self-framing open — see [aesGcmOpen].
 *
 * @throws VerificationFailed if authentication fails — opaque.
 * @throws UnsupportedOperationException if [supportsSyncChaChaPoly] is `false` (e.g. web).
 */
fun chaChaPolyOpen(
    sealed: ReadBuffer,
    key: ChaChaPolyKey,
    aad: ReadBuffer? = null,
    factory: BufferFactory = BufferFactory.Default,
): PlatformBuffer {
    if (!supportsSyncChaChaPoly) {
        throw UnsupportedOperationException("ChaCha20-Poly1305 is not supported on this platform")
    }
    val (nonce, ctAndTag, ptLen) = splitFramed(sealed)
    val out = factory.allocate(ptLen)
    chaChaPolyOpen(key, nonce, aad, ctAndTag, out)
    out.resetForRead()
    return out
}

// =============================================================================
// Async one-shot wrappers — work on EVERY platform (incl. browser/WebCrypto)
// =============================================================================

/**
 * AES-GCM seal that works on every platform, including browsers where the synchronous path is
 * unavailable. On native platforms it simply calls the synchronous [aesGcmSeal]; on js/wasmJs
 * it routes through WebCrypto's async `SubtleCrypto.encrypt`. Returns a `nonce ‖ ct ‖ tag`
 * buffer, like the sync helper.
 */
expect suspend fun aesGcmSealAsync(
    key: AesGcmKey,
    plaintext: ReadBuffer,
    aad: ReadBuffer? = null,
    factory: BufferFactory = BufferFactory.Default,
): PlatformBuffer

/**
 * AES-GCM open that works on every platform — the async counterpart of [aesGcmSeal] /
 * [aesGcmSealAsync]. Plaintext is returned only if the tag verifies.
 *
 * @throws VerificationFailed if authentication fails — opaque.
 */
expect suspend fun aesGcmOpenAsync(
    sealed: ReadBuffer,
    key: AesGcmKey,
    aad: ReadBuffer? = null,
    factory: BufferFactory = BufferFactory.Default,
): PlatformBuffer

/**
 * ChaCha20-Poly1305 seal, async surface. Provided for API symmetry with the AES path, but
 * ChaCha20-Poly1305 is **not** in WebCrypto: on js/wasmJs this throws
 * [UnsupportedOperationException] (never polyfilled). On native platforms it delegates to
 * the synchronous [chaChaPolySeal].
 *
 * @throws UnsupportedOperationException on js/wasmJs (and any platform where [supportsChaChaPoly] is `false`).
 */
expect suspend fun chaChaPolySealAsync(
    key: ChaChaPolyKey,
    plaintext: ReadBuffer,
    aad: ReadBuffer? = null,
    factory: BufferFactory = BufferFactory.Default,
): PlatformBuffer

/**
 * ChaCha20-Poly1305 open, async surface. See [chaChaPolySealAsync] — throws on the web.
 *
 * @throws VerificationFailed if authentication fails — opaque.
 * @throws UnsupportedOperationException on js/wasmJs.
 */
expect suspend fun chaChaPolyOpenAsync(
    sealed: ReadBuffer,
    key: ChaChaPolyKey,
    aad: ReadBuffer? = null,
    factory: BufferFactory = BufferFactory.Default,
): PlatformBuffer

// =============================================================================
// Internal explicit-nonce async primitives (KAT / Wycheproof seam)
// =============================================================================
//
// These let a caller (and the cross-platform vector tests) drive AES-GCM with a fixed,
// caller-supplied nonce on EVERY platform, including the web where only the async WebCrypto
// path exists. They are deliberately `internal`: the public seal API generates its own nonce
// so a (key, nonce) pair cannot be reused by accident. A vendored RFC/NIST/Wycheproof vector,
// by contrast, pins the nonce, so the test harness needs this seam.

/**
 * Encrypts [plaintext] with AES-GCM under [key] and the explicit [nonce], returning a
 * read-ready `ciphertext ‖ tag` buffer (no nonce prefix). [nonce] must be [AEAD_NONCE_BYTES]
 * bytes. Works on every platform (native: sync JCA/CommonCrypto; web: async WebCrypto).
 */
internal expect suspend fun aesGcmSealWithNonceAsync(
    key: AesGcmKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    plaintext: ReadBuffer,
    factory: BufferFactory,
): PlatformBuffer

/**
 * Decrypts an AES-GCM `ciphertext ‖ tag` blob under [key] and the explicit [nonce], returning
 * the recovered plaintext. Plaintext is produced only if the tag verifies.
 *
 * @throws VerificationFailed if authentication fails — opaque.
 */
internal expect suspend fun aesGcmOpenWithNonceAsync(
    key: AesGcmKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    ciphertextAndTag: ReadBuffer,
    factory: BufferFactory,
): PlatformBuffer

// =============================================================================
// Internal framing helpers (shared by sync + native async)
// =============================================================================

/** Allocates a `nonce ‖ ciphertext ‖ tag` buffer sized for [plaintextLen] bytes of plaintext. */
internal fun allocateFramed(
    plaintextLen: Int,
    factory: BufferFactory,
): PlatformBuffer = factory.allocate(AEAD_NONCE_BYTES + plaintextLen + AEAD_TAG_BYTES)

/**
 * Writes a fresh CSPRNG nonce at [dest]'s current position (advancing past it) and returns a
 * read-ready [AEAD_NONCE_BYTES]-byte view of just-written nonce for use as the seal nonce.
 */
internal fun writeFreshNonce(dest: WriteBuffer): ReadBuffer {
    val nonce = cryptoRandom(AEAD_NONCE_BYTES)
    // Bulk-copy the nonce into dest's framing slot, then hand back the standalone nonce buffer.
    // copyInto is non-destructive, so the returned nonce stays read-ready at position 0.
    copyInto(nonce, dest)
    return nonce
}

/** Decomposes a `nonce ‖ ciphertext ‖ tag` buffer into (nonce, ciphertext‖tag, plaintextLen). */
internal fun splitFramed(sealed: ReadBuffer): FramedParts {
    val total = sealed.remaining()
    require(total >= AEAD_NONCE_BYTES + AEAD_TAG_BYTES) {
        "sealed buffer too short: need at least ${AEAD_NONCE_BYTES + AEAD_TAG_BYTES} bytes, has $total"
    }
    val start = sealed.position()
    val nonce = sliceView(sealed, start, AEAD_NONCE_BYTES)
    val ctAndTagLen = total - AEAD_NONCE_BYTES
    val ctAndTag = sliceView(sealed, start + AEAD_NONCE_BYTES, ctAndTagLen)
    val plaintextLen = ctAndTagLen - AEAD_TAG_BYTES
    return FramedParts(nonce, ctAndTag, plaintextLen)
}

/** A non-destructive read-ready view of [length] bytes of [source] starting at absolute [from]. */
private fun sliceView(
    source: ReadBuffer,
    from: Int,
    length: Int,
): ReadBuffer {
    val savedPos = source.position()
    val savedLimit = source.limit()
    source.position(from)
    source.setLimit(from + length)
    val view = source.slice()
    source.position(savedPos)
    source.setLimit(savedLimit)
    return view
}

internal class FramedParts(
    val nonce: ReadBuffer,
    val ciphertextAndTag: ReadBuffer,
    val plaintextLen: Int,
) {
    operator fun component1() = nonce

    operator fun component2() = ciphertextAndTag

    operator fun component3() = plaintextLen
}
