package com.ditchoom.buffer.crypto

import com.ditchoom.buffer.BufferFactory
import com.ditchoom.buffer.Default
import com.ditchoom.buffer.PlatformBuffer
import com.ditchoom.buffer.ReadBuffer
import com.ditchoom.buffer.WriteBuffer

/*
 * Authenticated Encryption with Associated Data (AEAD).
 *
 * This file owns the AEAD primitive family: AES-GCM (128/256-bit keys) and ChaCha20-Poly1305
 * (IETF). Each algorithm is wrapped over the platform's native stack — JCA (AES/GCM/NoPadding,
 * ChaCha20-Poly1305) on JVM/Android, CommonCrypto/CryptoKit on Apple, BoringSSL on Linux, and
 * WebCrypto (AES-GCM) on js/wasmJs.
 *
 * Operations are reached through **capability witnesses**, not throwing top-level functions: the
 * platform's witness ([CryptoCapabilities.aesGcm] / [CryptoCapabilities.chaChaPoly]) reifies what
 * that platform supports as a `sealed` value, so an operation a platform lacks (a synchronous path
 * on the web, ChaCha at all on the web) is simply not reachable — the variance lives in the type,
 * not in a runtime throw. A consumer `when`s over the witness exhaustively and the compiler proves
 * every path is satisfiable. See [Aead] / [OptionalAead].
 *
 * Security contract (uniform across platforms):
 *  - Plaintext is released only after the tag verifies. open() performs a native one-shot
 *    decrypt; there is no unverified-plaintext streaming. A bad tag, tampered ciphertext,
 *    swapped AAD, or wrong key all surface as the same opaque [VerificationFailed] with no
 *    distinguishing reason — a granular reason on a verify path is a decryption oracle.
 *  - Nonces are CSPRNG-generated by the witness ops. seal draws a fresh 12-byte nonce from the
 *    library CSPRNG and prepends it to the output, so a caller cannot accidentally reuse one. The
 *    explicit-nonce path is internal (the KAT/Wycheproof + HPKE seam) — reusing a (key, nonce)
 *    pair with GCM or ChaCha20-Poly1305 is catastrophic (see the threat model).
 *  - Fixed 96-bit nonce, fixed 128-bit tag. Any other nonce length is rejected; truncated tags
 *    are never produced or accepted.
 *  - Typed, sized keys. [AesGcmKey] carries its 128/256-bit size and [ChaChaPolyKey] is a distinct
 *    type, so a key for one algorithm/size cannot be silently used for another.
 *
 * Output framing — the self-framing witness ops emit: nonce(12) ‖ ciphertext ‖ tag(16), so the
 * sealed buffer is self-describing and open needs no separate nonce argument.
 */

/** AEAD nonce/IV length in bytes (96-bit, the only length these wrappers accept). */
const val AEAD_NONCE_BYTES: Int = 12

/** AEAD authentication-tag length in bytes (128-bit, fixed). */
const val AEAD_TAG_BYTES: Int = 16

/** Key length in bytes for AES-128-GCM. */
const val AES_128_KEY_BYTES: Int = 16

/** Key length in bytes for AES-256-GCM. */
const val AES_256_KEY_BYTES: Int = 32

/** Key length in bytes for ChaCha20-Poly1305 (always 256-bit). */
const val CHACHA_KEY_BYTES: Int = 32

// =============================================================================
// Key types (sealed: only library-provided keys; impls are internal)
// =============================================================================

/**
 * Marker for every AEAD key type. `sealed` so a third party cannot supply an attacker-controlled
 * key implementation, and so the op interfaces can be generic over `K : AeadKey`.
 */
sealed interface AeadKey

/**
 * An AES-GCM key, carrying its [sizeBits] so a 128-bit key can never be silently used where a
 * 256-bit key was meant (or vice versa), and its [provenance] (software/hardware).
 *
 * This is a `sealed interface`; the only implementation downstream can construct is the in-memory
 * one produced by [of] (its concrete type is module-internal). Because downstream cannot name the
 * implementations, it cannot write an exhaustive `when` over them — which is what lets a
 * hardware-backed variant be added later as a non-breaking minor.
 *
 * In-memory key material is **not** auto-wiped — callers that need erase-on-free should allocate
 * the backing buffer from a secure factory and pass it through [of]; the copy taken there
 * preserves that secure backing.
 */
sealed interface AesGcmKey :
    AeadKey,
    AutoCloseable {
    /** 128 or 256 — the AES key size in bits. */
    val sizeBits: Int

    /** Whether the key material is in software memory or hardware-backed. */
    val provenance: KeyProvenance

    /** Key size in bytes (16 for AES-128, 32 for AES-256). */
    val sizeBytes: Int get() = sizeBits / 8

    companion object {
        /**
         * Wraps [key]'s remaining bytes as an in-memory AES-GCM key. The length must be exactly 16
         * (AES-128) or 32 (AES-256) bytes; any other length is rejected. The bytes are copied into
         * a buffer from [factory] (use a secure factory for erase-on-free).
         */
        fun of(
            key: ReadBuffer,
            factory: BufferFactory = BufferFactory.Default,
        ): SyncCapableAesGcmKey {
            val n = key.remaining()
            require(n == AES_128_KEY_BYTES || n == AES_256_KEY_BYTES) {
                "AES-GCM key must be $AES_128_KEY_BYTES or $AES_256_KEY_BYTES bytes, was $n"
            }
            return InMemoryAesGcmKey(n * Byte.SIZE_BITS, copyMaterial(key, factory))
        }
    }
}

/**
 * An [AesGcmKey] whose key material lives in process memory, so the **synchronous** AEAD ops can read
 * it directly. Only the in-memory key produced by [AesGcmKey.of] is a [SyncCapableAesGcmKey]; a
 * hardware-backed key is an [AesGcmKey] but not this, so the blocking witness ops
 * ([AeadBlockingOps.sealBlocking] / [AeadBlockingOps.openBlocking], which take the sync-capable type)
 * are statically unreachable for it — routing a hardware key into the synchronous path is a compile
 * error rather than a runtime throw. The async witness ops still serve both kinds.
 */
sealed interface SyncCapableAesGcmKey : AesGcmKey

/** In-memory [AesGcmKey]: holds the raw key bytes, freed (and wiped, on a secure buffer) on [close]. */
internal class InMemoryAesGcmKey(
    override val sizeBits: Int,
    val material: PlatformBuffer,
) : SyncCapableAesGcmKey {
    override val provenance: KeyProvenance get() = KeyProvenance.Software
    private var closed = false

    override fun close() {
        if (!closed) {
            closed = true
            material.freeNativeMemory()
        }
    }
}

/**
 * A ChaCha20-Poly1305 (IETF) key — always 256-bit. A distinct type from [AesGcmKey] so the two
 * AEAD families cannot be cross-used. `sealed` with an internal in-memory impl, like [AesGcmKey].
 */
sealed interface ChaChaPolyKey :
    AeadKey,
    AutoCloseable {
    /** Whether the key material is in software memory or hardware-backed. */
    val provenance: KeyProvenance

    companion object {
        /**
         * Wraps [key]'s remaining bytes as an in-memory ChaCha20-Poly1305 key. The length must be
         * exactly 32 bytes; any other length is rejected. The bytes are copied into a buffer from
         * [factory] (use a secure factory for erase-on-free).
         */
        fun of(
            key: ReadBuffer,
            factory: BufferFactory = BufferFactory.Default,
        ): ChaChaPolyKey {
            val n = key.remaining()
            require(n == CHACHA_KEY_BYTES) {
                "ChaCha20-Poly1305 key must be $CHACHA_KEY_BYTES bytes, was $n"
            }
            return InMemoryChaChaPolyKey(copyMaterial(key, factory))
        }
    }
}

/** In-memory [ChaChaPolyKey]: holds the raw key bytes, freed (and wiped) on [close]. */
internal class InMemoryChaChaPolyKey(
    val material: PlatformBuffer,
) : ChaChaPolyKey {
    override val provenance: KeyProvenance get() = KeyProvenance.Software
    private var closed = false

    override fun close() {
        if (!closed) {
            closed = true
            material.freeNativeMemory()
        }
    }
}

/**
 * The in-memory key material, for the blocking native primitives. A hardware-backed key (added
 * later) holds no exportable material and would route through the async provider path instead, so
 * this seam is only reached for in-memory keys.
 */
internal fun AesGcmKey.requireInMemoryMaterial(): PlatformBuffer =
    when (this) {
        is InMemoryAesGcmKey -> material
        // A hardware key holds no exportable material, so the synchronous/material-reading path is
        // not supported for it — hardware keys operate only through the async witness ops, which
        // dispatch to the gated closures and never reach here. This throw is the safety net if a
        // caller routes a hardware key into a blocking op (e.g. AES-GCM is Blocking on the JVM).
        is HardwareAesGcmKey -> throw UnsupportedOperationException("hardware AES-GCM key has no synchronous path")
    }

/** See [AesGcmKey.requireInMemoryMaterial]. */
internal fun ChaChaPolyKey.requireInMemoryMaterial(): PlatformBuffer =
    when (this) {
        is InMemoryChaChaPolyKey -> material
    }

/**
 * Seals [plaintext] through a hardware key's gated closure. The closure returns the fully framed
 * `nonce ‖ ciphertext ‖ tag` directly — the secure element picks the nonce itself (a keystore key
 * generates its own GCM IV; the library must never hand it one, since a single reused GCM nonce is
 * catastrophic), so this is a passthrough. Shared by the async- and blocking-witness ops so a
 * hardware key behaves the same regardless of which witness resolved.
 */
private suspend fun HardwareAesGcmKey.sealFramed(
    plaintext: ReadBuffer,
    aad: Aad,
    factory: BufferFactory,
): PlatformBuffer = gatedSeal(aad.bytesOrNull, plaintext, factory)

/** Opens a `nonce ‖ ciphertext ‖ tag` buffer through a hardware key's gated closure. */
private suspend fun HardwareAesGcmKey.openFramed(
    sealed: ReadBuffer,
    aad: Aad,
    factory: BufferFactory,
): PlatformBuffer {
    val (nonce, ctAndTag, _) = splitFramed(sealed)
    return gatedOpen(nonce, aad.bytesOrNull, ctAndTag, factory)
}

/** Copies [source]'s remaining bytes into a fresh read-ready buffer (non-destructive). */
private fun copyMaterial(
    source: ReadBuffer,
    factory: BufferFactory,
): PlatformBuffer = copyBuffer(source, factory)

// =============================================================================
// Capability witnesses: operations live ON the witness the platform supplies
// =============================================================================

/**
 * AEAD operations available through *some* path. Both seal and open are `suspend`; on platforms
 * with a synchronous native AEAD the witness is an [AeadBlockingOps], which adds the non-suspend
 * entry points.
 *
 * seal returns a self-framing `nonce ‖ ciphertext ‖ tag` buffer (fresh CSPRNG nonce); open
 * consumes that framing and needs no separate nonce.
 */
interface AeadAsyncOps<K : AeadKey> {
    /** Seals [plaintext] under [key], returning `nonce ‖ ciphertext ‖ tag` (fresh nonce). */
    suspend fun seal(
        key: K,
        plaintext: ReadBuffer,
        aad: Aad = Aad.None,
        factory: BufferFactory = BufferFactory.Default,
    ): PlatformBuffer

    /** Opens a `nonce ‖ ciphertext ‖ tag` buffer; plaintext is returned only if the tag verifies. */
    suspend fun open(
        sealed: ReadBuffer,
        key: K,
        aad: Aad = Aad.None,
        factory: BufferFactory = BufferFactory.Default,
    ): PlatformBuffer
}

/**
 * AEAD with a synchronous (non-`suspend`) path, in addition to the inherited async one.
 *
 * The synchronous ops are bound to [KSync] — the *sync-capable* subtype of the key family ([K]) whose
 * material is in process memory. For AES-GCM that is [SyncCapableAesGcmKey] (a hardware key is [K] but
 * not [KSync], so it cannot reach the blocking ops); for families with no hardware variant (ChaCha)
 * [KSync] is just [K]. The inherited async [seal] / [open] still serve the full [K] family.
 */
interface AeadBlockingOps<K : AeadKey, KSync : K> : AeadAsyncOps<K> {
    /** Synchronous [AeadAsyncOps.seal]; only a sync-capable [KSync] key can reach it. */
    fun sealBlocking(
        key: KSync,
        plaintext: ReadBuffer,
        aad: Aad = Aad.None,
        factory: BufferFactory = BufferFactory.Default,
    ): PlatformBuffer

    /** Synchronous [AeadAsyncOps.open]; only a sync-capable [KSync] key can reach it. */
    fun openBlocking(
        sealed: ReadBuffer,
        key: KSync,
        aad: Aad = Aad.None,
        factory: BufferFactory = BufferFactory.Default,
    ): PlatformBuffer
}

/**
 * Capability witness for an AEAD that is available on **every** platform (AES-GCM): it is either
 * synchronous ([Blocking], native) or async-only ([AsyncOnly], web). There is no `Unavailable`
 * variant because the algorithm is always present in some form.
 *
 * Carries the sync-capable key type [KSync] as a second parameter so that, after matching [Blocking],
 * a consumer can call [AeadBlockingOps.sealBlocking] with a concrete [KSync] key — a hardware key is
 * [K] but not [KSync], so it is rejected at compile time rather than throwing at the material seam.
 */
sealed interface Aead<K : AeadKey, KSync : K> {
    /** Async-only (e.g. WebCrypto). Only [AeadAsyncOps] is reachable. */
    data class AsyncOnly<K : AeadKey, KSync : K>(
        val ops: AeadAsyncOps<K>,
    ) : Aead<K, KSync>

    /** A synchronous native path is available; [ops] also satisfies [AeadAsyncOps]. */
    data class Blocking<K : AeadKey, KSync : K>(
        val ops: AeadBlockingOps<K, KSync>,
    ) : Aead<K, KSync>
}

/**
 * Capability witness for an AEAD that may be **absent** on a platform (ChaCha20-Poly1305 is not in
 * WebCrypto and is never polyfilled, so it is [Unavailable] on the web). When present it is either
 * [Blocking] or [AsyncOnly], as for [Aead].
 */
sealed interface OptionalAead<out K : AeadKey> {
    /** The algorithm is not available on this platform (cannot be reached at all). */
    data object Unavailable : OptionalAead<Nothing>

    /** Async-only path available. */
    data class AsyncOnly<K : AeadKey>(
        val ops: AeadAsyncOps<K>,
    ) : OptionalAead<K>

    /**
     * Synchronous native path available. The optional AEADs have no hardware-backed variant, so every
     * key is sync-capable and the blocking ops are bound to the full key family ([AeadBlockingOps]'s
     * second parameter is just [K]).
     */
    data class Blocking<K : AeadKey>(
        val ops: AeadBlockingOps<K, K>,
    ) : OptionalAead<K>
}

/**
 * The AES-GCM capability on this platform: [Aead.Blocking] on JVM/Android/Apple/Linux,
 * [Aead.AsyncOnly] on js/wasmJs (WebCrypto's `SubtleCrypto` is `suspend`-only). Always present. The
 * sync-capable key type is [SyncCapableAesGcmKey], so a hardware key cannot reach the blocking ops.
 */
expect val CryptoCapabilities.aesGcm: Aead<AesGcmKey, SyncCapableAesGcmKey>

/**
 * The ChaCha20-Poly1305 capability on this platform: [OptionalAead.Blocking] on
 * JVM(11+)/Android/Apple/Linux, [OptionalAead.Unavailable] on js/wasmJs.
 */
expect val CryptoCapabilities.chaChaPoly: OptionalAead<ChaChaPolyKey>

// =============================================================================
// Witness op implementations (common — call the per-platform expect primitives)
// =============================================================================

/** AES-GCM ops over the synchronous native primitives. Native async == sync. */
internal object AesGcmBlockingOps : AeadBlockingOps<AesGcmKey, SyncCapableAesGcmKey> {
    override fun sealBlocking(
        key: SyncCapableAesGcmKey,
        plaintext: ReadBuffer,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer {
        val out = allocateFramed(plaintext.remaining(), factory)
        val nonce = writeFreshNonce(out)
        aesGcmSeal(key, nonce, aad.bytesOrNull, plaintext, out)
        out.resetForRead()
        return out
    }

    override fun openBlocking(
        sealed: ReadBuffer,
        key: SyncCapableAesGcmKey,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer {
        val (nonce, ctAndTag, ptLen) = splitFramed(sealed)
        val out = factory.allocate(ptLen)
        aesGcmOpen(key, nonce, aad.bytesOrNull, ctAndTag, out)
        out.resetForRead()
        return out
    }

    // A hardware key is async-only (no in-process material for the blocking primitive), so even on a
    // Blocking platform its async seal/open route through the gated closures, not sealBlocking.
    override suspend fun seal(
        key: AesGcmKey,
        plaintext: ReadBuffer,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer =
        when (key) {
            is InMemoryAesGcmKey -> sealBlocking(key, plaintext, aad, factory)
            is HardwareAesGcmKey -> key.sealFramed(plaintext, aad, factory)
        }

    override suspend fun open(
        sealed: ReadBuffer,
        key: AesGcmKey,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer =
        when (key) {
            is InMemoryAesGcmKey -> openBlocking(sealed, key, aad, factory)
            is HardwareAesGcmKey -> key.openFramed(sealed, aad, factory)
        }
}

/** AES-GCM ops over the async explicit-nonce seam (WebCrypto). Generates + frames the nonce here. */
internal object AesGcmAsyncOps : AeadAsyncOps<AesGcmKey> {
    override suspend fun seal(
        key: AesGcmKey,
        plaintext: ReadBuffer,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer =
        when (key) {
            is InMemoryAesGcmKey -> {
                // Generate the nonce here so a (key, nonce) pair can never be reused by accident, then
                // frame as nonce ‖ ciphertext ‖ tag (the with-nonce helper returns ciphertext ‖ tag).
                val nonce = cryptoRandom(AEAD_NONCE_BYTES)
                val ctTag = aesGcmSealWithNonceAsync(key, nonce, aad.bytesOrNull, plaintext, factory)
                val out = allocateFramed(plaintext.remaining(), factory)
                out.write(nonce)
                out.write(ctTag)
                out.resetForRead()
                out
            }
            // A hardware key has no in-process material, so it routes through its gated closure;
            // adding HardwareAesGcmKey forces this branch (the sealed-impl point).
            is HardwareAesGcmKey -> key.sealFramed(plaintext, aad, factory)
        }

    override suspend fun open(
        sealed: ReadBuffer,
        key: AesGcmKey,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer =
        when (key) {
            is InMemoryAesGcmKey -> {
                val (nonce, ctAndTag, _) = splitFramed(sealed)
                aesGcmOpenWithNonceAsync(key, nonce, aad.bytesOrNull, ctAndTag, factory)
            }
            is HardwareAesGcmKey -> key.openFramed(sealed, aad, factory)
        }
}

/** ChaCha20-Poly1305 ops over the synchronous native primitives (never web). */
internal object ChaChaPolyBlockingOps : AeadBlockingOps<ChaChaPolyKey, ChaChaPolyKey> {
    override fun sealBlocking(
        key: ChaChaPolyKey,
        plaintext: ReadBuffer,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer {
        val out = allocateFramed(plaintext.remaining(), factory)
        val nonce = writeFreshNonce(out)
        chaChaPolySeal(key, nonce, aad.bytesOrNull, plaintext, out)
        out.resetForRead()
        return out
    }

    override fun openBlocking(
        sealed: ReadBuffer,
        key: ChaChaPolyKey,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer {
        val (nonce, ctAndTag, ptLen) = splitFramed(sealed)
        val out = factory.allocate(ptLen)
        chaChaPolyOpen(key, nonce, aad.bytesOrNull, ctAndTag, out)
        out.resetForRead()
        return out
    }

    override suspend fun seal(
        key: ChaChaPolyKey,
        plaintext: ReadBuffer,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer = sealBlocking(key, plaintext, aad, factory)

    override suspend fun open(
        sealed: ReadBuffer,
        key: ChaChaPolyKey,
        aad: Aad,
        factory: BufferFactory,
    ): PlatformBuffer = openBlocking(sealed, key, aad, factory)
}

// =============================================================================
// Low-level one-shot primitives (synchronous, native-or-throw) — internal seam
// =============================================================================
//
// These remain `internal`: the witness ops above (and the HPKE per-message AEAD glue) drive them.
// They are explicit-nonce by design — the public seal path generates its own nonce.

// Availability is read off the AEAD capability witness rather than standalone boolean flags: the
// witness ([CryptoCapabilities.aesGcm] / [CryptoCapabilities.chaChaPoly]) is the single source of
// truth for what each platform supports. These internal helpers exist for the in-module consumers
// (HPKE gating, the explicit-nonce glue, and test skip-gating) that need a plain boolean.

/** Whether AES-GCM has a synchronous path here (the witness is [Aead.Blocking]). */
internal val aesGcmBlockingAvailable: Boolean get() = CryptoCapabilities.aesGcm is Aead.Blocking

/** Whether ChaCha20-Poly1305 is reachable on any path here (the witness is not [OptionalAead.Unavailable]). */
internal val chaChaPolyReachable: Boolean get() = CryptoCapabilities.chaChaPoly !is OptionalAead.Unavailable

/** Whether ChaCha20-Poly1305 has a synchronous path here (the witness is [OptionalAead.Blocking]). */
internal val chaChaPolyBlockingAvailable: Boolean get() = CryptoCapabilities.chaChaPoly is OptionalAead.Blocking

/**
 * Seals [plaintext] with AES-GCM under [key] and [nonce], writing `ciphertext ‖ tag` into [dest]
 * at its current position. [nonce] must be exactly [AEAD_NONCE_BYTES] bytes.
 */
internal expect fun aesGcmSeal(
    key: AesGcmKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    plaintext: ReadBuffer,
    dest: WriteBuffer,
)

/**
 * Opens an AES-GCM `ciphertext ‖ tag` blob under [key], [nonce], and [aad], writing the recovered
 * plaintext into [dest] **only if the tag verifies**.
 *
 * @throws VerificationFailed if authentication fails — opaque.
 */
internal expect fun aesGcmOpen(
    key: AesGcmKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    ciphertextAndTag: ReadBuffer,
    dest: WriteBuffer,
)

/** ChaCha20-Poly1305 counterpart of [aesGcmSeal]. */
internal expect fun chaChaPolySeal(
    key: ChaChaPolyKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    plaintext: ReadBuffer,
    dest: WriteBuffer,
)

/**
 * ChaCha20-Poly1305 counterpart of [aesGcmOpen].
 *
 * @throws VerificationFailed if authentication fails — opaque.
 */
internal expect fun chaChaPolyOpen(
    key: ChaChaPolyKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    ciphertextAndTag: ReadBuffer,
    dest: WriteBuffer,
)

// =============================================================================
// Internal explicit-nonce async primitives (KAT / Wycheproof + HPKE seam)
// =============================================================================
//
// These drive AES-GCM with a fixed, caller-supplied nonce on EVERY platform, including the web
// where only the async WebCrypto path exists. Deliberately `internal`.

/**
 * Encrypts [plaintext] with AES-GCM under [key] and the explicit [nonce], returning a read-ready
 * `ciphertext ‖ tag` buffer (no nonce prefix). Works on every platform.
 */
internal expect suspend fun aesGcmSealWithNonceAsync(
    key: AesGcmKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    plaintext: ReadBuffer,
    factory: BufferFactory,
): PlatformBuffer

/**
 * Decrypts an AES-GCM `ciphertext ‖ tag` blob under [key] and the explicit [nonce], returning the
 * recovered plaintext. Plaintext is produced only if the tag verifies.
 *
 * @throws VerificationFailed if authentication fails — opaque.
 */
internal expect suspend fun aesGcmOpenWithNonceAsync(
    key: AesGcmKey,
    nonce: ReadBuffer,
    aad: ReadBuffer?,
    ciphertextAndTag: ReadBuffer,
    factory: BufferFactory,
): PlatformBuffer

// =============================================================================
// Internal framing helpers (shared by the witness ops)
// =============================================================================

/** Allocates a `nonce ‖ ciphertext ‖ tag` buffer sized for [plaintextLen] bytes of plaintext. */
internal fun allocateFramed(
    plaintextLen: Int,
    factory: BufferFactory,
): PlatformBuffer = factory.allocate(AEAD_NONCE_BYTES + plaintextLen + AEAD_TAG_BYTES)

/**
 * Writes a fresh CSPRNG nonce at [dest]'s current position (advancing past it) and returns a
 * read-ready [AEAD_NONCE_BYTES]-byte view of the just-written nonce for use as the seal nonce.
 */
internal fun writeFreshNonce(dest: WriteBuffer): ReadBuffer {
    val nonce = cryptoRandom(AEAD_NONCE_BYTES)
    // Bulk-copy the nonce into dest's framing slot, then hand back the standalone nonce buffer.
    // copyInto is non-destructive, so the returned nonce stays read-ready at position 0.
    copyInto(nonce, dest)
    return nonce
}

/** Decomposes a `nonce ‖ ciphertext ‖ tag` buffer into (nonce, ciphertext‖tag, plaintextLen). */
internal fun splitFramed(sealed: ReadBuffer): FramedParts {
    val total = sealed.remaining()
    require(total >= AEAD_NONCE_BYTES + AEAD_TAG_BYTES) {
        "sealed buffer too short: need at least ${AEAD_NONCE_BYTES + AEAD_TAG_BYTES} bytes, has $total"
    }
    val start = sealed.position()
    val nonce = sliceView(sealed, start, AEAD_NONCE_BYTES)
    val ctAndTagLen = total - AEAD_NONCE_BYTES
    val ctAndTag = sliceView(sealed, start + AEAD_NONCE_BYTES, ctAndTagLen)
    val plaintextLen = ctAndTagLen - AEAD_TAG_BYTES
    return FramedParts(nonce, ctAndTag, plaintextLen)
}

/** A non-destructive read-ready view of [length] bytes of [source] starting at absolute [from]. */
private fun sliceView(
    source: ReadBuffer,
    from: Int,
    length: Int,
): ReadBuffer {
    val savedPos = source.position()
    val savedLimit = source.limit()
    source.position(from)
    source.setLimit(from + length)
    val view = source.slice()
    source.position(savedPos)
    source.setLimit(savedLimit)
    return view
}

internal class FramedParts(
    val nonce: ReadBuffer,
    val ciphertextAndTag: ReadBuffer,
    val plaintextLen: Int,
) {
    operator fun component1() = nonce

    operator fun component2() = ciphertextAndTag

    operator fun component3() = plaintextLen
}
