@file:OptIn(ExperimentalForeignApi::class)

package com.ditchoom.buffer.crypto

import com.ditchoom.buffer.crypto.CryptoTestVectors.hexBuffer
import com.ditchoom.buffer.crypto.CryptoTestVectors.toHex
import kotlinx.cinterop.ByteVar
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.allocArray
import kotlinx.cinterop.get
import kotlinx.cinterop.memScoped
import kotlinx.cinterop.set
import kotlinx.cinterop.toKString
import kotlinx.coroutines.test.runTest
import platform.posix.mkdtemp
import platform.posix.remove
import platform.posix.rmdir
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Linux on-disk [PosixFileKeyStorage] round-trips: a key generated by one store instance survives
 * being dropped and re-opened from the same directory — the real "reload across launches" the
 * in-memory conformance suite can only simulate — plus the SPKI public identity export.
 */
class PosixFileKeyStoreTest {
    private val dir: String =
        memScoped {
            val template = "/tmp/buffer-crypto-ks-XXXXXX"
            val buf = allocArray<ByteVar>(template.length + 1)
            for (i in template.indices) buf[i] = template[i].code.toByte()
            buf[template.length] = 0
            requireNotNull(mkdtemp(buf)).toKString()
        }

    private fun store() = CryptoCapabilities.keyStore(KeyStoreConfig(location = dir))

    @AfterTest
    fun cleanup() {
        for (alias in listOf("identity", "data")) remove("$dir/$alias.key")
        rmdir(dir)
    }

    @Test
    fun signingKeyPersistsAcrossStoreInstances() =
        runTest {
            val generated = store().getOrGenerateSigning("identity", SignatureScheme.EcdsaP256)
            val spki = generated.verifyKey.exportSpki().toHex()
            generated.close()

            // A brand-new store over the same directory reloads the same key + public identity.
            val reloaded = assertNotNull(store().loadSigning("identity"))
            assertEquals(spki, reloaded.verifyKey.exportSpki().toHex())
            val msg = hexBuffer("cafebabe")
            assertTrue(verifyAsync(reloaded.verifyKey, msg, signAsync(reloaded, msg)))

            // Idempotent get-or-generate over the reloaded store does not mint a new key.
            assertEquals(
                spki,
                store()
                    .getOrGenerateSigning("identity", SignatureScheme.EcdsaP256)
                    .verifyKey
                    .exportSpki()
                    .toHex(),
            )
        }

    @Test
    fun aesKeyPersistsAndDeletes() =
        runTest {
            val store = store()
            val original = store.getOrGenerateAesGcm("data")
            val ops =
                when (val w = CryptoCapabilities.aesGcm) {
                    is Aead.Blocking -> w.ops
                    is Aead.AsyncOnly -> w.ops
                }
            val plaintext = "6f70656e2d6d652d6166746572"
            val sealed = ops.seal(original, hexBuffer(plaintext))

            val reloaded = assertNotNull(store().loadAesGcm("data"))
            assertEquals(plaintext, ops.open(sealed, reloaded).toHex())

            assertTrue(store.delete("data"))
            assertFalse(store.contains("data"))
        }
}
