package com.ditchoom.buffer.crypto

import com.ditchoom.buffer.crypto.CryptoTestVectors.hexBuffer
import com.ditchoom.buffer.crypto.CryptoTestVectors.toHex
import kotlinx.coroutines.test.runTest
import java.nio.file.Files
import kotlin.io.path.absolutePathString
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * JVM on-disk [FileKeyStorage] round-trips: a key generated by one store instance survives being
 * dropped and re-opened from the same directory — the real "reload across launches" the in-memory
 * conformance suite can only simulate. Also asserts the public identity export (SPKI) reloads.
 */
class FileKeyStoreTest {
    private val dir = Files.createTempDirectory("buffer-crypto-keystore-test")

    private fun store() = CryptoCapabilities.keyStore(KeyStoreConfig(location = dir.absolutePathString()))

    @AfterTest
    fun cleanup() {
        Files.walk(dir).sorted(Comparator.reverseOrder()).forEach { Files.deleteIfExists(it) }
    }

    @Test
    fun signingKeyPersistsAcrossStoreInstances() =
        runTest {
            val generated = store().getOrGenerateSigning("identity", SignatureScheme.EcdsaP256)
            val spki = generated.verifyKey.exportSpki().toHex()
            generated.close()

            // A brand-new store over the same directory reloads the same key + public identity.
            val reloaded = assertNotNull(store().loadSigning("identity"))
            assertEquals(spki, reloaded.verifyKey.exportSpki().toHex())
            val msg = hexBuffer("cafebabe")
            assertTrue(verifyAsync(reloaded.verifyKey, msg, signAsync(reloaded, msg)))

            // Idempotent get-or-generate over the reloaded store does not mint a new key.
            assertEquals(
                spki,
                store()
                    .getOrGenerateSigning("identity", SignatureScheme.EcdsaP256)
                    .verifyKey
                    .exportSpki()
                    .toHex(),
            )
        }

    @Test
    fun aesKeyPersistsAndDeletes() =
        runTest {
            val sealed =
                store().getOrGenerateAesGcm("data").let { key ->
                    when (val w = CryptoCapabilities.aesGcm) {
                        is Aead.Blocking -> w.ops
                        is Aead.AsyncOnly -> w.ops
                    }.seal(key, hexBuffer("0011223344"))
                }
            val reloaded = assertNotNull(store().loadAesGcm("data"))
            val opened =
                when (val w = CryptoCapabilities.aesGcm) {
                    is Aead.Blocking -> w.ops
                    is Aead.AsyncOnly -> w.ops
                }.open(sealed, reloaded)
            assertEquals("0011223344", opened.toHex())

            assertTrue(store().delete("data"))
            assertFalse(store().contains("data"))
            assertTrue(Files.list(dir).use { it.count() } == 0L, "the .key file must be gone from disk")
        }

    @Test
    fun aliasesListsWhatIsOnDisk() =
        runTest {
            store().getOrGenerateSigning("alpha", SignatureScheme.EcdsaP256)
            store().getOrGenerateKeyAgreement("beta", KeyAgreementCurve.P256)
            assertEquals(setOf("alpha", "beta"), store().aliases())
        }
}
