name: "Build and Test"
on:
  pull_request:
    paths-ignore:
      - '*.md'
    types:
      - synchronize
      - opened
jobs:
  review:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '19'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Tests with Gradle Major
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: ./gradlew ktlintCheck assemble build check allTests publishToMavenLocal -PincrementMajor=true
      - name: Tests with Gradle Minor
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: ./gradlew ktlintCheck assemble build check allTests publishToMavenLocal -PincrementMinor=true
      - name: Tests with Gradle Patch
        if: !contains(github.event.pull_request.labels.*.name, 'major') && !contains(github.event.pull_request.labels.*.name, 'minor')
        run: ./gradlew ktlintCheck assemble build check allTests publishToMavenLocal
